package marketing

import "errors"

var (
	ErrInvalidFundingMode                  = errors.New("invalid funding mode")
	ErrInvalidCampaignStatus                = errors.New("invalid campaign status")
	ErrInvalidDiscountType                  = errors.New("invalid discount type")
	ErrFixedDiscountNotAllowed              = errors.New("fixed discount is not supported for platform-funded campaigns in V1")
	ErrZamkShareExceedsCeiling              = errors.New("requested ZAMK share exceeds maximum ceiling of 25% (2500 bps)")
	ErrSellerFundedCannotHaveZamk           = errors.New("seller-funded campaigns cannot have ZAMK subsidy or budget")
	ErrApprovedExceedsRequested             = errors.New("approved financial terms cannot exceed requested terms")
	ErrInvalidBudgetCap                     = errors.New("approved ZAMK budget cap must be greater than zero for approved platform funding")
	ErrCustomerPriceNegative                = errors.New("customer price cannot become negative")
	ErrCampaignNotFound                     = errors.New("marketing campaign not found")
	ErrPromoCodeNotFound                    = errors.New("promo code not found")
	ErrPromoCodeDuplicate                   = errors.New("promo code already exists")
	ErrOpenPlatformFundingExists            = errors.New("seller already has an active or submitted platform-funded campaign")
	ErrCounterOfferInvalidState             = errors.New("counter offer can only be accepted or rejected in counter_offered status")
	ErrSellerUnauthorized                   = errors.New("seller is not authorized to modify this campaign")
	ErrCannotMutateApprovedFields           = errors.New("seller cannot mutate admin-approved financial fields")
	ErrInvalidPriceHistory                  = errors.New("invalid price history record")
	ErrInvalidOrderItemPromotion            = errors.New("invalid order item promotion snapshot")
	ErrCofundedRequiresSellerContribution   = errors.New("cofunded campaign requires positive seller discount percentage")
	ErrSellerRequiresDiscount               = errors.New("seller-funded campaign must specify positive discount")
	ErrZamkCannotHaveSellerDiscount         = errors.New("platform-funded campaign cannot have seller discount")
	ErrSubmittedPlatformRequiresRequested   = errors.New("submitted platform-funded campaign requires positive requested share and budget cap")
	ErrUnreviewedMustHaveZeroApproved       = errors.New("unreviewed platform campaign must have zero approved terms")

	// Runtime Checkout Promo Errors
	ErrPromoNotFound             = errors.New("promo_not_found")
	ErrPromoInactive             = errors.New("promo_inactive")
	ErrPromoNotStarted           = errors.New("promo_not_started")
	ErrPromoExpired              = errors.New("promo_expired")
	ErrPromoMinSubtotal          = errors.New("promo_min_subtotal")
	ErrPromoGlobalLimit          = errors.New("promo_global_limit")
	ErrPromoCustomerLimit        = errors.New("promo_customer_limit")
	ErrPromoFirstOrderOnly       = errors.New("promo_first_order_only")
	ErrPromoNotApplicable        = errors.New("promo_not_applicable")
	ErrPromoBudgetExhausted      = errors.New("promo_budget_exhausted")
	ErrPromoOrderAlreadyHasPromo = errors.New("promo_order_already_has_promo")
	ErrPromoUsageNotFound        = errors.New("promo_usage_not_found")
	ErrPromoUsageNotReserved     = errors.New("promo_usage_not_reserved")

	// Seller Promo Management Errors
	ErrImmutableFieldCannotBeChanged = errors.New("economic and identity fields are immutable after creation")
	ErrGlobalLimitBelowUsage         = errors.New("global usage limit cannot be lower than current committed usage")
	ErrCustomerLimitBelowUsage       = errors.New("per customer usage limit cannot be lower than current customer usage")
	ErrInvalidDates                  = errors.New("ends_at must be strictly after starts_at")
	ErrPromoAlreadyExpired           = errors.New("cannot create an already expired promo code")
	ErrInvalidDiscountValue          = errors.New("invalid discount value")
	ErrInvalidLimit                  = errors.New("usage limit must be positive")
	ErrProductNotOwnedBySeller       = errors.New("one or more products do not belong to the seller")
	ErrInvalidProductScope           = errors.New("invalid product scope")
	ErrProductConflict               = errors.New("product cannot be simultaneously included and excluded")
	ErrInvalidMaxDiscount            = errors.New("max discount must be positive")
)
